### ISSUE TITLE
增加统一的获取设备ID方法

### ISSUE THREAD

**Issue by tourze** [wangheng3751/react-native-mixpush#1]
现在rn这边可以直接使用setAlias来设置别名，然后后端通过别名来推送。
如果后端希望通过设备ID来推送，则需要客户端这边主动上报，目前react-native-mixpush没对应方法获取，希望可以支持~

**Comment by wangheng3751** [comment]
嗯，各个平台的处理方式不一样，已在新版本中试图统一处理此问题，但还是有瑕疵，具体说明在readme中，希望能有帮助！
