### ISSUE TITLE
构建报错

### ISSUE THREAD

**Issue by jiushicheng** [wangheng3751/react-native-mixpush#2]
Android Studio 构建的时候报错。和华为推送有关
Failed to resolve: com.huawei.android.hms:push:2.5.2.300。
Failed to resolve: com.getui:sdk:2.11.1.0

**Comment by wangheng3751** [comment]
检查一下maven配置，看一下ReadMe中的第三步，配置maven库地址的地方配置了没有。

**Comment by jiushicheng** [comment]
加了maven 的华为配置。但是 http://developer.huawei.com/repo/ 这个地址用浏览器也找不到

**Comment by wangheng3751** [comment]
http://developer.huawei.com/consumer/cn/service/hms/catalog/huaweipush_agent.html?page=hmssdk_huaweipush_devprepare_agent
这个是华为官方接入指南  地址 http://developer.huawei.com/repo/  和官方一样没错，可能是官方maven服务不稳定。

**Comment by jiushicheng** [comment]
你那本地能打开这个地址吗

**Comment by wangheng3751** [comment]
打不开 但是我编译能过

**Comment by jiushicheng** [comment]
你网络翻墙了吗

**Comment by wangheng3751** [comment]
没有翻墙

**Comment by jiushicheng** [comment]
编译问题解决。还有新疑问是华为手机不支持得到(cid)的方法。你怎么拿到deviceToken

**Comment by wangheng3751** [comment]
NativeAppEventEmitter.addListener( 'receiveClientId', (cid) => { alert("cid:"+cid);//自行处理cid代码 } );
华为在推送注册成功后会收到事件，事件携带deviceToken；
ReadMe中第七步有说明。

**Comment by jiushicheng** [comment]
如何判断是否注册成功。。以下方法和注册有关系吗。
MixPush.setAlias(alias); //设置别名<br>
MixPush.unsetAlias(alias); //取消设置别名<br>
MixPush.setTags(tags); //设置用户标签<br>
MixPush.unsetTags(tags); //取消设置用户标签<br>
MixPush.getClientId(); //获取客户端ID<br>
我现在监听写在app一运行起来的时候。app一运行华为就注册了吗？

**Comment by wangheng3751** [comment]
是的  如果APPID等各项配置正常 在APP启动时就会注册

**Comment by jiushicheng** [comment]
OK。那设置别名的那些方法和注册有关系吗？注册成功收到监听的'receiveClientId'事件，只在注册成功收到一次吗？

**Comment by wangheng3751** [comment]
@jiushicheng  那些和注册没关系 是的 receiveClientId事件只在注册成功后收到（理论上是各大厂商推送都会回调这个事件） 针对华为就在receiveClientId事件中处理cid  其他手机还可以调用getClientId主动获取

**Comment by jiushicheng** [comment]
你有微信或者qq吗？ 我现在在app 启动页的constructor上就开始调用      NativeAppEventEmitter.addListener( 'receiveClientId', (cid) => {
        alert(cid);
      })
但是 没有看见alert事件

**Comment by jiushicheng** [comment]
@wangheng3751 也就现在只是加了监听。也没看懂哪里调用了这个监听函数

**Comment by wangheng3751** [comment]
@jiushicheng  
刚刚建了个QQ群 进来看看能不能帮你吧
群号：516032289

**Comment by jiushicheng** [comment]
OK
